services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7410
      POSTGRES_DB: invoice
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    depends_on:
      postgresdb:
        condition: service_healthy
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:7410@postgresdb:5432/invoice?schema=public"
    ports: 
      - 3000:3000
      - 3001:3001
    
    stdin_open: true
    tty: true

volumes:
  db:
